#!/bin/bash

set -e

if [[ $(git diff --shortstat 2> /dev/null | tail -n1) != "" ]]; then
    echo "You have uncommmited changes; please add/commit first."
    exit 1
fi

make clean

echo "$1" > VERSION
git commit -am "bumped version to v$1"
git tag "v$1"
git push --tags

# compile released binaries for all platforms
make release

# set everything back to dev
echo "dev" > VERSION
git commit -am "set version to dev"

git push
